// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'link-button': string;
  'pagination-style': string;
  'responsive-content': string;
  'table-style': string;
}
export const cssExports: CssExports;
export default cssExports;
